apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:r7AwW5ERSLH5C6iPShzxLlqe8I+fv1ycBTg2DvGGD6KfrdgPvg5yRA==,iv:0OfiF5tzAXgAM4z6LpbpG5kIUsL0d+PPDW+ljokAGS4=,tag:97GUi05+XtXcbEcfxHL91w==,type:str]
sops:
  age:
    - recipient: age1kzgg3943q86kcll3h68z0ld4q7v8mwjgchx0uarqgny9k7usmffs0tq9pg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZnppdjM3UGVTbzFrRXdj
        VUhIdUl1LzVXR0ZwZUNTakJHSjM3OXJVeEZJCit5S3RWVkQrbEMvaHlrbzg0aWZQ
        djlwaXVNdDFteFhzOXBZUnBEQ1JTYlEKLS0tIG4xVGdTTk1lNVNMVng3TFNlbVly
        bG02WWhUb3Z2ZGs4ZnJRZXNycktQK2cKae0e7FB6imTgvxVCJKqxnyrfSTnuUynR
        CYYyzvORyLZhERae7cGXglYO6Su8QHUJVE4s0hgICKPBp+hitqEerQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-12T10:20:20Z"
  mac: ENC[AES256_GCM,data:T4PxPpTrs10OaZWE1eNiuW21nKYRkVoY4sGS8DONO/SSsxsE6Laq3EeFntwvnAXlxcYjiBgutBU6MyOQG0eSKUV7OgbVKCYmirdahohGeXoIraTqUPSA5TYYHNP/vm2kj1O3DesbJX2rqv61/fWmtyxSyyAgPA36Ltu/yrWykoE=,iv:g1XnvdxImCz2tT8XekjaQIT3BWSTGB6/iUB++AGfv3s=,tag:2EtHBtpSeyJq0NX7MBx5lg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
