apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:FA6ENWCACvm0v8NyIDZVx4yloe+uL8e2u0SZF8wVOfo=,iv:sR0Kaqybhn4McSjCcnpt6EeyxbUn7LF2AljGoPnv278=,tag:1mly9RHYRUhsm6WaFDyHbQ==,type:str]
sops:
  age:
    - recipient: age1kzgg3943q86kcll3h68z0ld4q7v8mwjgchx0uarqgny9k7usmffs0tq9pg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMDIzNExoWVJQSTVndmpI
        SHRpNTltUzhUS0JTamlGVTF4TGNNU1BaRXkwCnlhVHc4NEJKeUJOdkFSNkhhOCtX
        TXRLL2NOV3Qxc3cxeVpkMC90UHBvK1kKLS0tIHRCbCt6MFRUTnFxYW11VDVvekhp
        Smg1c3ZMMTR6dWIxNlRXVzIzVEtScnMK+wu7v6E5MWmgaK3eWi9kXMBcgF/r4NWd
        PXiKEj1x6Tuhs9CbX4Q6go7HUUSsiP//Z68Ak8Av5UJlDmjTtfK4hg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-12T10:20:20Z"
  mac: ENC[AES256_GCM,data:lB9RZS2fJxQgXup7J6/JxE+MsD/6AQeUYkO08GKd6BoPHtLR1mFmlTAaAJbFNVjUeJ7sWUcx8dqcC2cyV9lcJKnihZeMNQh+k0fVlTIDCk/CeVDIpDRj07YjvJog24vlBZRJYyYUlGIILV2CNHu16lo5KGv9SO6dbMtq2nekwsM=,iv:Asr9haYiwyUHIWqMIQkwi+chuf3nWOVWvUN8UaU3LvM=,tag:BuyPKcUSe3xSp9nJ1FSfVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
