apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:++vbF1I+LwNTURoC2vtj8VHc/5VpzDPDJMr9vjDnnDtYKRdww/7R5uQo6eBqXj4SnSZA/lcgiL3jGZGEP7kkDv8GIeIl/el4Bcx/uLZs3w2ikjWFCweQBkhwi7WsgWiTCn058uOI7RkHoTd6QVvdkr3L3nNdwUbJienHOuxDRkf65JsLCj5mZ0iiPvnWs3wvxOdUMGbj3ELs6JoOQ4Sf70DXlrVp9ja2iPE1ts92jBE23kmH,iv:2UcpfGhsdf9ofkmJnhSO6/AopUmYQXU3+0D1Xb5rEtc=,tag:EePHhWMFINRgGAtY/s9KcQ==,type:str]
sops:
  age:
    - recipient: age1kzgg3943q86kcll3h68z0ld4q7v8mwjgchx0uarqgny9k7usmffs0tq9pg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZG9OQ0NlSTg1M1pmVDUv
        NzdrenpjeklESE1SOGZPS0JFaDd1UGR5bnhFCjV0ajhHS3BiM1UyMnA3U2FlU3hv
        ekYxMXVydmZmV0RWWW5ySWNuSndEUlUKLS0tIFJYRGlUdjJQQnE5dmhKaDNiczh4
        b1ZRNVFzV0xHaFI3emNQMTB3a1NsOEUKP44pZcsQJBwAgAO/AR0DO0x5HeUJ6dgX
        YTKT4eJzuvaidtktuEXVjkwrcOXoOcivSlDwyTSf8Ynv0Y6nQ/Yv+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-12T10:20:20Z"
  mac: ENC[AES256_GCM,data:8t8VnMEj24kAEvsO2qA0o1F41VqJ2GpD3oxjCaHH1eqUeO+eHvRm+MuTX8wIqtulJdtZgIer6eLYt1kBs7m0DI4VNgY68F+ce246hVLodG02ApiDaEeuEzqxmb/UgWkDqzEC+aS2RQcmbrpv1RGyPdRfkHQrcsS55IrRI4qES50=,iv:6TvND14XcADescYTzEfBV+mjtvxK1JBP7FGf7C+iQpo=,tag:84XFVdE712axYhJAFwgm5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
