apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:mGKOm1Zi2OqKS1/bi5hkJh1CckjHaSC3HzWRV7gGDWGrndkbGqAklw==,iv:lUxSlDx1fbkD94VjfG2MLeNpsx6My+r2i4ftLQSJFXo=,tag:0EUZP5X4knVKer6r9xCV9g==,type:str]
sops:
  age:
    - recipient: age1kzgg3943q86kcll3h68z0ld4q7v8mwjgchx0uarqgny9k7usmffs0tq9pg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRlhVVGNCZHFwWVRkNFlN
        Z2dodUUzcU9PVUt2Q3ZaSWNDRGRkTjE0Q3dVCjhJU2MvM3MrM0QyYTJxeXJJVzJl
        TGJGVWZURURLZlFEU2NuKzVGak52TmcKLS0tIHp2YnBKUFNCTXJlRTlHbkhkN1Rx
        QTVpOTdiRUFmQmRtY2lPY3FjUW5maU0K4/qg4bxG034uNGt4U0LnVP5doQMLjrEJ
        8DWGl7N9HmkcPz88zsQ/ACwvw5CiGWgs6oXNPrlBZRhihQSVz3XhZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-12T10:20:20Z"
  mac: ENC[AES256_GCM,data:osKX1pbGT8Jz13s9HsDXuSUwO9ZVfWxDO3d1wouMe2FMmv8jLdli1tTGSpAa2Ihe0/uZjpHHeXZ9ecLmQCdBmzVuYiDbAOMoS7CwPnFUzinMsl3teMZlRTT62IJFLBzZ19FabXsTRDGQeCAGP6yjQngmD5DeYN+RUZzTGlGFf84=,iv:uwn8+UzaI0EjK3mXGcty8dDLsFfyxJeASLUt2b784Fw=,tag:rDzk+rL/ZDLtbPfbou/srQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
